version: '3.1'

services:

#used by customer microservice
  mysql:
    container_name: foa-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      #MYSQL_USER: foa-customer
      #MYSQL_PASSWORD: foacustomer123
    ports:
      - '3306:3306'

#used by restaurant microservice
  mongo:
    container_name: foa_mongo
    image: mongo
    ports:
      - '27017:27017'

#used by restaurant microservice
  elasticsearch:
    container_name: foa_elasticsearch
    image: elasticsearch:7.4.2
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      discovery.type: single-node

#used by order microservice
  db:
    container_name: foa_postgresql
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin

#sql client for postgresql/mysql
  adminer:
    container_name: foa_adminer
    image: adminer
    restart: always
    ports:
      - 9080:8080

  msrabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=foa
      - RABBITMQ_DEFAULT_PASS=foa

#zipkin server for tracing
  zipkin:
    container_name: foa_zipkin
    image: openzipkin/zipkin
    ports:
      - 9411:9411


